### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IvanFon** [machinamentum/CTR64#8]
Are there plans to add an open-source license soon?

**Comment by machinamentum** [comment]
This project has always been under Beerware (see [here](https://github.com/machinamentum/CTR64/blob/master/source/main.cpp#L1-L8)). There's no plans to use a different license as many licenses tend to (in my opinion):
* Be overly complicated
* Impose an overbearing responsibility on to the user to not misrepresent the software
* Suggest that the open source nature of the software implies more freedom to the user while also forcing the user to comply with a set of rules to preserve that open source nature (which seems counterintuitive).

The main goal is to keep the project closely to or in the public domain. If there's intent on using it for commercial purposes and Beerware/public domain doesn't sit well with a company's lawyers, I'm open to dual-licensing the project under another low-maintenance license.
